### ISSUE TITLE
CSS 单行，多行溢出隐藏

### ISSUE THREAD

**Issue by hanekaoru** [hanekaoru/blog#3]
单行，多行溢出隐藏在 `Web` 开发过程中是一个十分常见的需求

在 `WebKit` 浏览器或移动端（绝大部分是 `WebKit` 内核的浏览器）的页面实现比较简单，可以直接使用 `WebKit` 的 `CSS` 扩展属性(`WebKit` 是私有属性) 

```css
-webkit-line-clamp
```

但是需要注意的是，这是一个**不规范的属性**（`unsupported WebKit property`），它并没有出现在 `CSS` 规范草案中

`-webkit-line-clamp` 用来**限制在一个块元素显示的文本的行数**，为了实现该效果，它需要组合其他的 `WebKit` 属性

常见结合属性有以下几种

* `display: -webkit-box`  必须结合的属性，将对象作为弹性伸缩盒子模型显示

* `-webkit-box-orient`  必须结合的属性 ，设置或检索伸缩盒对象的子元素的排列方式

* `text-overflow: ellipsis`  可以用来多行文本的情况下，用省略号 "..." 隐藏超出范围的文本

一般多行溢出常用的代码如下：

```css
p {
  overflow : hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```

修改一下就可以实现单行溢出隐藏

```css
p {
  text-overflow: ellipsis;
  overflow: hidden;
  word-break: break-all;
  white-space: normal;
}
```

或者使用 `jQuery` 来做限制：

```js
/* 
  $(".test1").wordLimit();     自动获取 css 宽度进行处理，如果 css 中未对 .test1 给定宽度，则不起作用
  $(".test2").wordLimit(24);   截取字符数，值为大于 0 的整数，这里表示 class 为 test2 的标签内字符数最多 24 个
*/
(function ($) {
  $.fn.wordLimit = function (num) {
    this.each(function () {
      if (!num) {
        var copyThis = $(this.cloneNode(true)).hide().css({
          'position': 'absolute',
          'width': 'auto',
          'overflow': 'visible'
        });

        $(this).after(copyThis);

        if (copyThis.width() > $(this).width()) {
          $(this).text($(this).text().substring(0, $(this).text().length - 4));
          $(this).html($(this).html() + '...');
          copyThis.remove();
          $(this).wordLimit();
        } else {
          // 清除复制
          copyThis.remove();
          return;
        }

      } else {
        var maxwidth = num;

        if ($(this).text().length > maxwidth) {
          $(this).text($(this).text().substring(0, maxwidth));
          $(this).html($(this).html() + '...');
        }
      }
    });
  }
})(jQuery);
```
