### ISSUE TITLE
:host 和 ::ng-deep

### ISSUE THREAD

**Issue by hanekaoru** [hanekaoru/blog#34]
这里会涉及到 `Angular` 的 `ViewEncapsulation`，即封装模式，主要分为三种

详细可以参考 [Angular 中的 ViewEncapsulation](https://github.com/hanekaoru/WebLearningNotes/blob/master/angular/note/Angular/00.md#23-angular-中的-viewencapsulation)

* `Native` 原先浏览器 `Shadow DOM` 行为

* `Emulated` 仿真模式，通过 `Angular` 来模拟类似 `Shadow DOM` 的行为

* `None` 无任何封装行为

唯一的区别在于 `Shadow DOM`，当然其作用是让组件的样式只进不出，换言之即组件内的样式不会影响到外部组件

三者的表现形成如下，假设基本模版为

```js
@Component({
  template: `<h1>test</h1>`,
  styles: [`h1 { color: #f50; }`],
  encapsulation: ViewEncapsulation.Native
})
```

三种方式生成的分别为

#### Native

```html
#shadow-root (open)
  <style>h1 { color: #f50; }</style>

  <h1>test</h1>
```

#### Emulated

```html
<style>h1[_ngcontent-c0] { color: #f50; }</style>

<h1 _ngcontent-c0>test</h1>
```

#### None

```html
<style>h1 { color: #f50; }</style>

<h1>test</h1>
```

需要注意的是：`Native` 和 `None` 在内容是一样的，但其后者会影响至其他外部组件的 `h1` 元素

## 组件样式

组件样式的封装模式取决于我们对 `encapsulation` 的配置，当然你可以了在 `main.ts` 时为所有组件统一设定一种行的模式，例如

```js
// 使用 None 模式
platformBrowserDynamic().bootstrapModule(AppModule, {
  defaultEncapsulation: ViewEncapsulation.None
})
```

虽然三种模式都有不同的风格，但对于一个组件而言，如果没有一很合理的使用风格在实际项目中会让我们很头疼，特别是当项目中同时在使用第三方组件库，情况会更为复杂

比如你在某一个组件当中添加了一个 `class` 样式

```css
.active-link {
  color: red;
}
```

若组件设定为 `None` 模式，只要该组件出现过一次，并且在未来所有即使不再使用，那么这个样式也会得到保留，所有的添加了这个 `class` 的元素均会改变

反之，对于 `Shadow` 行为，它会为该组件创建一个额外的属性 `_ngcontent-c1` 来标识（不管是 `Native`、`Emulated` 本质是一样的）所设定的样式仅限于当前组件当中

而 `Angular` 中即采用 `:host` 来表示组件自身，所以前面的 `CSS` 样式可以调整为

```css
:host .active-link {
  color: red;
}

<!-- 生成的样式为 -->

[_nghost-c1] .active-link[_ngcontent-c1] {
  color: red;
}
```

然而我们会发现，对于第三方组件组件而言，`.active-link` 是其组件内部某个 `HTML` 元素的 `class` 而已，且它有自己的一套组件封装规则

但我们生成的 `CSS` 中包括了一个奇怪的字符 `[_ngcontent-c1]`，最终导致该组件样式无法改变内嵌的第三方组件内容的样式

在这种情况下，`Angular` 提供了一种对未来工具更好兼容性的命令 `::ng-deep` 来强制样式允许侵入子组件

```css
:host ::ng-deep .active-link {
  color: red;
}

<!-- 生成的样式为 -->

[_nghost-c1] .active-link {
  color: red;
}
```

最终的结果就是这个样式只会在这个组件内部当中有效
